force-app/main/default/objects/Desk__c/Desk__c.object-meta.xml
<CustomObject>
    <label>Desk</label>
    <nameField>
        <displayFormat>D-{00000}</displayFormat>
        <label>Desk</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Desks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Desk__c/fields/Desk_No__c.field-meta.xml
<CustomField>
    <fullName>Desk_No__c</fullName>
    <label>Desk No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Desk__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <label>Floor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Floor 1</fullName>
            </value>
            <value>
                <fullName>Floor 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Desk__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <label>Office</label>
    <referenceTo>Office__c</referenceTo>
    <relationshipLabel>Desk</relationshipLabel>
    <relationshipName>Desk</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Desk_Booking__c/Desk_Booking__c.object-meta.xml
<CustomObject>
    <label>Desk Booking</label>
    <nameField>
        <displayFormat>DB-{00000}</displayFormat>
        <label>Desk Booking No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Desk Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Desk_Booking__c/fields/Date_of_Booking__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Booking__c</fullName>
    <label>Date of Booking</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Desk_Booking__c/fields/Desk__c.field-meta.xml
<CustomField>
    <fullName>Desk__c</fullName>
    <label>Desk</label>
    <referenceTo>Desk__c</referenceTo>
    <relationshipLabel>Desk Bookings</relationshipLabel>
    <relationshipName>Desk_Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Desk_Booking__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Desk_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Office__c/Office__c.object-meta.xml
<CustomObject>
    <label>Office</label>
    <nameField>
        <label>Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offices</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Office__c/fields/Number_of_Columns__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Columns__c</fullName>
    <label>Number of Columns</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DeskBookingHelper.cls
/**
 * @description Helper class to support retrieve and manipulate Desk Booking data. Used within "deskBooking" lwc.
 */
public with sharing class DeskBookingHelper {

    @TestVisible
    private static Boolean simulateException = false;

    /**
     * @description Retrieves office records from the database. 
     *              Assumption: Maximum number of office records are limited to 10.
     */
    @AuraEnabled(cacheable=true)
    public static String getOffices() {
        try {
            if(simulateException) {
                throw new QueryException();
            }
            List<Office__c> offices = [SELECT Id, Name, Number_of_Columns__c FROM Office__c ORDER BY Name LIMIT 10 ];
            return JSON.serialize(offices);
        } catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }
    
    /**
     * @description Retrives desk records and related bookings for a given office and a date of booking.   
     */
    @AuraEnabled
    public static String getDeskBookingData(Id officeId, Date bookingDate) {
        try {
            if(bookingDate == null) {
                throw new AuraHandledException(System.Label.Booking_Date_Null);
            }
            List<Desk__c> desks = [SELECT Id, Name, Desk_No__c, Floor__c, Office__r.Number_of_Columns__c,
                (SELECT Id, Desk__c, User__c, User__r.Name, User__r.FirstName,  User__r.SmallPhotoUrl 
                    FROM Desk_Bookings__r WHERE Date_of_Booking__c = :bookingDate)
                FROM Desk__c WHERE Office__c = :officeId WITH SECURITY_ENFORCED ORDER BY Floor__c, Desk_No__c ];
            return JSON.serialize(desks);
        } catch (Exception ex) {
            System.debug(ex.getMessage()+'-'+ex.getStackTraceString());
            throw new AuraHandledException(ex.getMessage());
        }
    }

    /**
     * @description Creates a single desk booking for the currently logged in user,  
     *              for a given desk and a date. Also removes any existing bookings for that date
     *              as only one user can be booked in for a given desk on a single day.
     */
    @AuraEnabled
    public static void createDeskBooking(Id deskId, Date bookingDate) {
        if(bookingDate == null) {
            throw new AuraHandledException(System.Label.Booking_Date_Null);
        }
        try {
            ManageBookings.deleteBooking(deskId, bookingDate);
            ManageBookings.insertBooking(deskId, bookingDate);
        } catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }

    /**
     * @description Delete desk booking for the current user for a given desk and a date.
     */
    @AuraEnabled
    public static void deleteDeskBooking(Id deskId, Date bookingDate) {
        try {
            if(bookingDate == null) {
                throw new AuraHandledException(System.Label.Booking_Date_Null);
            }
            ManageBookings.deleteBooking(deskId, bookingDate);
        } catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }
}