force-app/main/default/objects/Desk__c/Desk__c.object-meta.xml
<CustomObject>
    <label>Desk</label>
    <nameField>
        <displayFormat>D-{00000}</displayFormat>
        <label>Desk</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Desks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Desk__c/fields/Desk_No__c.field-meta.xml
<CustomField>
    <fullName>Desk_No__c</fullName>
    <label>Desk No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Desk__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <label>Floor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Floor 1</fullName>
            </value>
            <value>
                <fullName>Floor 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Desk__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <label>Office</label>
    <referenceTo>Office__c</referenceTo>
    <relationshipLabel>Desk</relationshipLabel>
    <relationshipName>Desk</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Desk_Booking__c/Desk_Booking__c.object-meta.xml
<CustomObject>
    <label>Desk Booking</label>
    <nameField>
        <displayFormat>DB-{00000}</displayFormat>
        <label>Desk Booking No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Desk Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Desk_Booking__c/fields/Date_of_Booking__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Booking__c</fullName>
    <label>Date of Booking</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Desk_Booking__c/fields/Desk__c.field-meta.xml
<CustomField>
    <fullName>Desk__c</fullName>
    <label>Desk</label>
    <referenceTo>Desk__c</referenceTo>
    <relationshipLabel>Desk Bookings</relationshipLabel>
    <relationshipName>Desk_Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Desk_Booking__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Desk_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Office__c/Office__c.object-meta.xml
<CustomObject>
    <label>Office</label>
    <nameField>
        <label>Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offices</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Office__c/fields/Number_of_Columns__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Columns__c</fullName>
    <label>Number of Columns</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {

    public static final String FLOOR_1 = 'Floor 1';
    public static final String FLOOR_2 = 'Floor 2';

    public static User createUser(Boolean insertToDatabase, String profileName, String permissionSetName, String emailAddress, String userNameString, String alias){
        List<Profile> p = [SELECT Id FROM Profile WHERE Name = :profileName];
        Id queriedProfileId = p[0].Id;

        User u = new User(
            Alias = alias, 
            Email = emailAddress,
            EmailEncodingKey = 'UTF-8', 
            Lastname = 'TESTING-MVN-USR', 
            LanguageLocaleKey = 'en_US',
            LocaleSIDKey = 'en_US', 
            ProfileId = queriedProfileId,
            TimezoneSIDKey = 'America/Los_Angeles', 
            Username = userNameString);

        if(insertToDatabase) {
            insert u;
        }

        if(permissionSetName != null && insertToDatabase) {
            PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Id = :permissionSetName LIMIT 1];
            PermissionSetAssignment psa = new PermissionSetAssignment(PermissionSetId = ps.Id, AssigneeId = u.Id);
            insert psa;
        }
        return u;
    }

    public static Office__c createOffice(Boolean insertToDatabase, String name, Integer noOfCols) {
        Office__c office = new Office__c(Name = name, Number_of_Columns__c = noOfCols);

        if(insertToDatabase) {
            insert office;
        }
        return office;
    }

    public static List<Office__c> createOffices(Boolean insertToDatabase, String name, Integer noOfCols, Integer numberOfOffices) {
        List<Office__c> offices = new List<Office__c>();

        for(Integer i = 0; i < numberOfOffices; i++) {
            offices.add(createOffice(false, name + '' + i, noOfCols));
        }

        if(insertToDatabase) {
            insert offices;
        }

        return offices;
    }

    public static Desk__c createDesk(Boolean insertToDatabase, Id officeId, Integer deskNo, String floor) {
        Desk__c desk = new Desk__c(Office__c = officeId, Floor__c = floor, Desk_No__c = deskNo);

        if(insertToDatabase) {
            insert desk;
        }
        return desk;
    }

    public static List<Desk__c> createDesks(Boolean insertToDatabase, Id officeId, String floor, Integer numberOfDesks) {
        List<Desk__c> desks = new List<Desk__c> ();

        for(Integer i = 0; i < numberOfDesks; i++) {
            Desk__c desk = new Desk__c(Office__c = officeId, Floor__c = floor, Desk_No__c = i);
            desks.add(desk);
        }
        
        if(insertToDatabase) {
            insert desks;
        }
        return desks;
    }

    public static Desk_Booking__c createDeskBooking(Boolean insertToDatabase, Id deskId, Id userId, Date dateOfBooking) {

        Desk_Booking__c db = new Desk_Booking__c(Desk__c = deskId, User__c = userId, Date_of_Booking__c = dateOfBooking);

        if(insertToDatabase) {
            insert db;
        }

        return db;
    }
}