force-app/main/default/objects/Desk__c/Desk__c.object-meta.xml
<CustomObject>
    <label>Desk</label>
    <nameField>
        <displayFormat>D-{00000}</displayFormat>
        <label>Desk</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Desks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Desk_Booking__c/Desk_Booking__c.object-meta.xml
<CustomObject>
    <label>Desk Booking</label>
    <nameField>
        <displayFormat>DB-{00000}</displayFormat>
        <label>Desk Booking No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Desk Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Desk_Booking__c/fields/Date_of_Booking__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Booking__c</fullName>
    <label>Date of Booking</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Desk_Booking__c/fields/Desk__c.field-meta.xml
<CustomField>
    <fullName>Desk__c</fullName>
    <label>Desk</label>
    <referenceTo>Desk__c</referenceTo>
    <relationshipLabel>Desk Bookings</relationshipLabel>
    <relationshipName>Desk_Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Desk_Booking__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Desk_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ManageBookings.cls
public without sharing class ManageBookings {

    public static void deleteBooking(Id deskId, Date bookingDate) {
        List<Desk_Booking__c> existingBookings = [SELECT Id FROM Desk_Booking__c WHERE Date_of_Booking__c = :bookingDate AND User__c = :UserInfo.getUserId()];
        delete existingBookings;
    }

    public static Desk_Booking__c insertBooking(Id deskId, Date bookingDate) {
        Desk_Booking__c deskBooking = new Desk_Booking__c(
                Desk__c = deskId,
                User__c = UserInfo.getUserId(),
                Date_of_Booking__c = bookingDate);
        
            insert deskBooking;
        return deskBooking;
    } 
}