force-app/main/default/objects/Desk__c/Desk__c.object-meta.xml
<CustomObject>
    <label>Desk</label>
    <nameField>
        <displayFormat>D-{00000}</displayFormat>
        <label>Desk</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Desks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Desk__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <label>Office</label>
    <referenceTo>Office__c</referenceTo>
    <relationshipLabel>Desk</relationshipLabel>
    <relationshipName>Desk</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Desk_Booking__c/Desk_Booking__c.object-meta.xml
<CustomObject>
    <label>Desk Booking</label>
    <nameField>
        <displayFormat>DB-{00000}</displayFormat>
        <label>Desk Booking No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Desk Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Desk_Booking__c/fields/Date_of_Booking__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Booking__c</fullName>
    <label>Date of Booking</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Desk_Booking__c/fields/Desk__c.field-meta.xml
<CustomField>
    <fullName>Desk__c</fullName>
    <label>Desk</label>
    <referenceTo>Desk__c</referenceTo>
    <relationshipLabel>Desk Bookings</relationshipLabel>
    <relationshipName>Desk_Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Desk_Booking__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Desk_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Office__c/Office__c.object-meta.xml
<CustomObject>
    <label>Office</label>
    <nameField>
        <label>Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offices</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/ManageBookingsTest.cls
@isTest
private class ManageBookingsTest {

    @TestSetup
    private static void setupData() {
        User testUser = TestDataFactory.createUser(true, 'Standard Platform User', 'test@test.com', 'mvntest@test-ne2cv4zrs1g2.com', 'testmvnX');
        List<Office__c> offices = TestDataFactory.createOffices(true, 'Test Office', 4, 2);

        List<String> floors = new List<String>{TestDataFactory.FLOOR_1, TestDataFactory.FLOOR_1};
        List<Desk__c> desks = TestDataFactory.createDesks(true, offices, floors, 16);
        
        TestDataFactory.createDeskBooking(true, desks[0].Id, testUser.Id, Date.newInstance(2020, 01, 01));
        TestDataFactory.createDeskBooking(true, desks[1].Id, UserInfo.getUserId(), Date.newInstance(2020, 01, 02));
        TestDataFactory.createDeskBooking(true, desks[2].Id, UserInfo.getUserId(), Date.newInstance(2020, 01, 03));
    }

    private static User getRunningUser() {
        User testUser = [SELECT Id FROM User WHERE Username = 'mvntest@test-ne2cv4zrs1g2.com' LIMIT 1];
        TestDataFactory.assignPermissionSet(testUser.Id, 'Desk_Booking');
        return testUser;
    }

    @IsTest
    private static void testDeleteBooking() {
        User runningUser = getRunningUser();
        System.runAs(runningUser) {

            Desk_Booking__c booking = [SELECT Id, Desk__c FROM Desk_Booking__c WHERE User__c = :runningUser.Id LIMIT 1];
            Date dateOfBooking = Date.newInstance(2020, 01, 01);

            Test.startTest();
            ManageBookings.deleteBooking(booking.Desk__c, dateOfBooking);
            Test.stopTest();

            Desk_Booking__c[] newBooking = [SELECT Id, Desk__c, User__c, Date_of_Booking__c FROM Desk_Booking__c WHERE User__c = :runningUser.Id];
            
            System.assertEquals(0, newBooking.size(), 'Desk booking must be deleted.');
        }
    }

    @IsTest
    private static void testInsertBooking() {
        User runningUser = getRunningUser();
        System.runAs(runningUser) {

            Desk_Booking__c booking = [SELECT Id, Desk__c FROM Desk_Booking__c WHERE User__c = :runningUser.Id LIMIT 1];
            Desk__c newDesk = [SELECT Id FROM Desk__c WHERE Id != :booking.Desk__c LIMIT 1];
            Date dateOfBooking = Date.newInstance(2020, 01, 01);

            Test.startTest();
            ManageBookings.insertBooking(newDesk.Id, dateOfBooking);
            Test.stopTest();

            Desk_Booking__c[] newBooking = [SELECT Id, Desk__c, User__c, Date_of_Booking__c FROM Desk_Booking__c WHERE User__c = :runningUser.Id];
            System.assertEquals(2, newBooking.size(), 'Duplicate booking record created');
        }
    }
}